version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./testtask.db:/fastapi_app/testtask.db  # Привязываем файл базы данных к контейнеру
    environment:
      - PYTHONUNBUFFERED=1